echo "Set environment variables"
export NUM_EPOCHS=1
echo "--------------------------------------------------------------"
export CNN_WIDTH=11
#python3 main.py
echo "--------------------------------------------------------------"
export CNN_WIDTH=13
#python3 main.py
echo "--------------------------------------------------------------"
#export CNN_WIDTH=15
#python3 main.py
echo "--------------------------------------------------------------"
export CNN_WIDTH=17
python3 main.py
echo "--------------------------------------------------------------"
export CNN_WIDTH=19
#python3 main.py
echo "--------------------------------------------------------------"
export CNN_WIDTH=21
#python3 main.py